import {
  AttentionAudit,
  AudioQualityMetrics,
  QualityScoreProfile,
  ManualRubricParameters,
  GeneratedRoomFlow,
  RoomCategory,
  RoomSubCategory,
  RoomSubCategoryCode,
  MicroSpecialRequest,
} from "../types";
import { buildMeetingUrl } from "./domainService";

export const INITIAL_ATTENTION_AUDITS: Record<string, AttentionAudit> = {
  "host-1": {
    participantId: "host-1",
    name: "Dr. Evelyn Vance (Lead Facilitator)",
    role: "instructor",
    gaze: "center",
    headPose: { pitch: 1.2, yaw: -0.5, roll: 0.1 },
    blinkRate: 16,
    eyesOnScreen: true,
    attentionScore: 97,
    engagementLevel: "High Focus",
    distractionAlert: false,
    landmarks: {
      leftEye: [42, 38],
      rightEye: [58, 38],
      noseTip: [50, 48],
      mouthCenter: [50, 62],
      chin: [50, 78],
    },
  },
  "stu-1": {
    participantId: "stu-1",
    name: "Sophia Chen",
    role: "student",
    gaze: "center",
    headPose: { pitch: -0.8, yaw: 1.4, roll: -0.3 },
    blinkRate: 18,
    eyesOnScreen: true,
    attentionScore: 94,
    engagementLevel: "High Focus",
    distractionAlert: false,
    landmarks: {
      leftEye: [43, 39],
      rightEye: [57, 39],
      noseTip: [50, 49],
      mouthCenter: [50, 63],
      chin: [50, 77],
    },
  },
  "stu-2": {
    participantId: "stu-2",
    name: "Marcus Vance",
    role: "student",
    gaze: "screen-right",
    headPose: { pitch: 4.5, yaw: 14.2, roll: 2.1 },
    blinkRate: 24,
    eyesOnScreen: false,
    attentionScore: 72,
    engagementLevel: "Mild Distraction",
    distractionAlert: true,
    landmarks: {
      leftEye: [48, 38],
      rightEye: [63, 38],
      noseTip: [56, 49],
      mouthCenter: [55, 63],
      chin: [54, 76],
    },
  },
  "stu-3": {
    participantId: "stu-3",
    name: "Aria Thorne",
    role: "student",
    gaze: "down",
    headPose: { pitch: -12.4, yaw: 0.8, roll: -1.2 },
    blinkRate: 20,
    eyesOnScreen: true,
    attentionScore: 88,
    engagementLevel: "Attentive",
    distractionAlert: false,
    landmarks: {
      leftEye: [42, 44],
      rightEye: [58, 44],
      noseTip: [50, 54],
      mouthCenter: [50, 67],
      chin: [50, 81],
    },
  },
  "stu-4": {
    participantId: "stu-4",
    name: "Liam O'Connor",
    role: "student",
    gaze: "away",
    headPose: { pitch: 8.2, yaw: -22.5, roll: 5.4 },
    blinkRate: 11,
    eyesOnScreen: false,
    attentionScore: 54,
    engagementLevel: "Off-Task",
    distractionAlert: true,
    landmarks: {
      leftEye: [35, 36],
      rightEye: [49, 36],
      noseTip: [41, 48],
      mouthCenter: [42, 62],
      chin: [43, 75],
    },
  },
};

export const INITIAL_AUDIO_METRICS: Record<string, AudioQualityMetrics> = {
  "host-1": {
    participantId: "host-1",
    snrDb: 34,
    ambientNoiseDb: -52,
    packetLossPercent: 0.05,
    jitterMs: 3.2,
    audioLatencyMs: 14,
    vocalClarityGrade: "A+",
    clippingDetected: false,
    speechPaceWpm: 136,
  },
  "stu-1": {
    participantId: "stu-1",
    snrDb: 29,
    ambientNoiseDb: -46,
    packetLossPercent: 0.1,
    jitterMs: 4.8,
    audioLatencyMs: 18,
    vocalClarityGrade: "A",
    clippingDetected: false,
    speechPaceWpm: 124,
  },
  "stu-2": {
    participantId: "stu-2",
    snrDb: 21,
    ambientNoiseDb: -38,
    packetLossPercent: 1.2,
    jitterMs: 12.4,
    audioLatencyMs: 32,
    vocalClarityGrade: "B",
    clippingDetected: false,
    speechPaceWpm: 98,
  },
  "stu-3": {
    participantId: "stu-3",
    snrDb: 26,
    ambientNoiseDb: -42,
    packetLossPercent: 0.4,
    jitterMs: 6.2,
    audioLatencyMs: 22,
    vocalClarityGrade: "A",
    clippingDetected: false,
    speechPaceWpm: 118,
  },
  "stu-4": {
    participantId: "stu-4",
    snrDb: 15,
    ambientNoiseDb: -31,
    packetLossPercent: 4.8,
    jitterMs: 28.5,
    audioLatencyMs: 64,
    vocalClarityGrade: "C",
    clippingDetected: true,
    speechPaceWpm: 60,
  },
};

export const INITIAL_QUALITY_PROFILES: Record<string, QualityScoreProfile> = {
  "host-1": {
    participantId: "host-1",
    participantName: "Dr. Evelyn Vance (Lead Facilitator)",
    role: "instructor",
    autoComputedScore: 96,
    manualRubricScore: 97,
    finalCompositeScore: 97,
    rubricBreakdown: {
      pedagogyDelivery: 25,
      studentInclusivity: 24,
      vocalClarityAcoustics: 25,
      screenEngagementPacing: 23,
    },
    evaluatorNotes: "Exemplary didactic pacing; pristine acoustic fidelity with zero packet degradation. Responsive in breakout guidance.",
    lastAuditedAt: "Today, 09:05 AM",
    auditorName: "Academic Quality Audit Cell (AQAC-21K)",
  },
  "stu-1": {
    participantId: "stu-1",
    participantName: "Sophia Chen",
    role: "student",
    autoComputedScore: 93,
    manualRubricScore: 92,
    finalCompositeScore: 92,
    rubricBreakdown: {
      pedagogyDelivery: 23,
      studentInclusivity: 23,
      vocalClarityAcoustics: 23,
      screenEngagementPacing: 23,
    },
    evaluatorNotes: "Consistently engaged; active note-taking and immediate response to interactive polls.",
    lastAuditedAt: "Today, 09:08 AM",
    auditorName: "Automated AI Gaze & Audio Observer",
  },
  "stu-2": {
    participantId: "stu-2",
    participantName: "Marcus Vance",
    role: "student",
    autoComputedScore: 74,
    manualRubricScore: 76,
    finalCompositeScore: 75,
    rubricBreakdown: {
      pedagogyDelivery: 19,
      studentInclusivity: 20,
      vocalClarityAcoustics: 19,
      screenEngagementPacing: 18,
    },
    evaluatorNotes: "Frequent right-hand gaze deviations detected (secondary monitor suspected). Raised hand to clarify doubts.",
    lastAuditedAt: "Today, 09:02 AM",
    auditorName: "Facilitator Dr. Evelyn Vance",
  },
  "stu-3": {
    participantId: "stu-3",
    participantName: "Aria Thorne",
    role: "student",
    autoComputedScore: 87,
    manualRubricScore: 86,
    finalCompositeScore: 86,
    rubricBreakdown: {
      pedagogyDelivery: 21,
      studentInclusivity: 22,
      vocalClarityAcoustics: 22,
      screenEngagementPacing: 21,
    },
    evaluatorNotes: "Down-gaze corresponds to textbook reading. Audio clear with slight packet jitter on entry.",
    lastAuditedAt: "Today, 09:14 AM",
    auditorName: "Automated AI Gaze & Audio Observer",
  },
  "stu-4": {
    participantId: "stu-4",
    participantName: "Liam O'Connor",
    role: "student",
    autoComputedScore: 56,
    manualRubricScore: 60,
    finalCompositeScore: 58,
    rubricBreakdown: {
      pedagogyDelivery: 15,
      studentInclusivity: 15,
      vocalClarityAcoustics: 15,
      screenEngagementPacing: 15,
    },
    evaluatorNotes: "Camera off / gaze away from stage viewport. High background noise (-31dB) requires facilitator audio intervention.",
    lastAuditedAt: "Today, 09:15 AM",
    auditorName: "Academic Quality Audit Cell (AQAC-21K)",
  },
};

export const SUB_CATEGORY_CODES: Record<RoomSubCategory, RoomSubCategoryCode> = {
  "Demo Classes": "DC",
  "Enrolled Classes": "PC",
  "Doubt Clearance Classes": "DCC",
  "Community Activities Classes": "CAC",
  "Student Collaboration Classes": "SCC",
};

export const buildStandardizedRoomLink = (
  category: RoomCategory,
  subCategory: RoomSubCategory,
  course: string,
  teacherName: string,
  timezone: string,
  specialRequest?: MicroSpecialRequest
) => {
  const subCode = SUB_CATEGORY_CODES[subCategory] || "PC";
  const sanitize = (s: string) =>
    s
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");

  const catPrefix = category === "21K School" ? "21k" : "floww";
  const courseSlug = sanitize(course).slice(0, 18);
  const teacherSlug = sanitize(teacherName.split(" ").pop() || "lead").slice(0, 10);
  const tzSlug = sanitize(timezone.split(" ")[0]);
  const reqSlug =
    specialRequest && specialRequest !== "General"
      ? `-${sanitize(specialRequest).slice(0, 12)}`
      : "";

  const roomCode = `${catPrefix.toUpperCase()}-${subCode}-${courseSlug.toUpperCase().slice(0, 8)}-${tzSlug.toUpperCase()}`;
  const roomUrl = buildMeetingUrl(`${catPrefix}-${subCode.toLowerCase()}-${courseSlug}-${teacherSlug}-${tzSlug}${reqSlug}`);

  return { roomCode, roomUrl, subCode };
};

export const INITIAL_GENERATED_ROOMS: GeneratedRoomFlow[] = [
  {
    id: "rf-1",
    name: "Grade 10-A Physics: Quantum Mechanics",
    category: "21K School",
    subCategory: "Enrolled Classes",
    subCategoryCode: "PC",
    microCategory: {
      course: "Advanced Quantum Mechanics & Physics",
      language: "English (Global)",
      timezone: "IST (UTC+5:30)",
      teacherId: "tch-1",
      teacherName: "Dr. Evelyn Vance",
      requestType: "General",
    },
    roomCode: "21K-PC-PHY101-IST",
    roomUrl: buildMeetingUrl("21k-pc-grade10-phys-vance-ist"),
    scheduledBreakMinutes: 10,
    activeBreak: false,
    createdAt: "Today, 08:30 AM",
    studentCapacity: 30,
    activeStudentsCount: 26,
  },
  {
    id: "rf-2",
    name: "Grade 9 Mathematics Interactive Demo",
    category: "21K School",
    subCategory: "Demo Classes",
    subCategoryCode: "DC",
    microCategory: {
      course: "Linear Algebra & Spatial Geometry",
      language: "English (Global)",
      timezone: "IST (UTC+5:30)",
      teacherId: "tch-2",
      teacherName: "Prof. Rajesh Sengupta",
      requestType: "General",
    },
    roomCode: "21K-DC-MATH9-IST",
    roomUrl: buildMeetingUrl("21k-dc-grade9-math-sengupta-ist"),
    scheduledBreakMinutes: 5,
    activeBreak: false,
    createdAt: "Today, 08:45 AM",
    studentCapacity: 50,
    activeStudentsCount: 42,
  },
  {
    id: "rf-3",
    name: "Molecular Chemistry Doubt Clearance",
    category: "21K School",
    subCategory: "Doubt Clearance Classes",
    subCategoryCode: "DCC",
    microCategory: {
      course: "Organic Synthesis & Molecular Orbitals",
      language: "English (Global)",
      timezone: "GMT (UTC+0)",
      teacherId: "tch-3",
      teacherName: "Dr. Ananya Iyer",
      requestType: "General",
    },
    roomCode: "21K-DCC-CHEM11-GMT",
    roomUrl: buildMeetingUrl("21k-dcc-chem-bonding-iyer-gmt"),
    scheduledBreakMinutes: 10,
    activeBreak: false,
    createdAt: "Today, 08:50 AM",
    studentCapacity: 15,
    activeStudentsCount: 11,
  },
  {
    id: "rf-4",
    name: "Global Youth Model UN & Rhetoric",
    category: "21K Learning Floww",
    subCategory: "Community Activities Classes",
    subCategoryCode: "CAC",
    microCategory: {
      course: "Global Diplomacy, Public Speaking & MUN",
      language: "English (Global)",
      timezone: "SGT (UTC+8)",
      teacherId: "tch-4",
      teacherName: "Kaelen Ray",
      requestType: "General",
    },
    roomCode: "FLOWW-CAC-DEBATE-SGT",
    roomUrl: buildMeetingUrl("floww-cac-debate-global-sgt"),
    scheduledBreakMinutes: 15,
    activeBreak: false,
    createdAt: "Today, 09:00 AM",
    studentCapacity: 40,
    activeStudentsCount: 38,
  },
  {
    id: "rf-5",
    name: "Autonomous Robotics Sprint (IEP Accommodated)",
    category: "21K Learning Floww",
    subCategory: "Student Collaboration Classes",
    subCategoryCode: "SCC",
    microCategory: {
      course: "Micro-Robotics & Sensor Interfacing",
      language: "English (Global)",
      timezone: "EST (UTC-5)",
      teacherId: "tch-1",
      teacherName: "Dr. Evelyn Vance",
      requestType: "Special Needs (IEP)",
    },
    roomCode: "FLOWW-SCC-ROBOT-EST",
    roomUrl: buildMeetingUrl("floww-scc-robotics-team-est-iep"),
    scheduledBreakMinutes: 10,
    activeBreak: false,
    createdAt: "Today, 09:10 AM",
    studentCapacity: 20,
    activeStudentsCount: 18,
  },
];
